version: '3'
services:
  gasazon-api:
    container_name: gasazon-api
    image: gasazon-api:1.0.0
    build: 
      target: production
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - noister-network

  mongo:
    image: mongo:latest
    container_name: noister-mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    networks:
      - noister-network

  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo

networks:
  noister-network: